### PR TITLE
ECCW-414: Provide way for editors to get to webform results

### PR DESCRIPTION
**Pull request by nbrettell**

### CODE REVIEW

**Comment by nbrettell** [comment]
You're right, I'm not sure why the export didn't include the addition of the new menu item. I'll take a further look at this

**Comment by siliconmeadow** [comment]
> You're right, I'm not sure why the export didn't include the addition of the new menu item. I'll take a further look at this

I don't think menu items are normally exportable to config. They're considered content. Menus are content. Menu items normally need an install hook for deployments. Perhaps this is a manual task on the cloud environments and we'll leave it at that?

**Comment by nbrettell** [comment]
I think the previous way I got this working was moving an already existing menu item, hence my confusion. Would it be simpler to provide a View and add this to the admin menu?

**Comment by siliconmeadow** [comment]
> 

Yeah, that was my original thinking when I made the ticket. I guess I should have been more explicit instead of saying TBD!

**Review by siliconmeadow — APPROVED** [review]

**Review by siliconmeadow — APPROVED** [review]
LGTM - thanks @nbrettell! :-)

**Pull request merged**
