### PR TITLE
Release/202312 01

### PR DESCRIPTION
**Pull request by markconroy**

### CODE REVIEW

**Comment by Polynya** [comment]
I've changed the PR to Draft so it is only merged to main after the release has been tested on Preprod.

**Comment by Polynya** [comment]
Hi Mark, I don't think we need the branches _release/202312-01_ and _release/202312-02_ anymore. The branch on Preprod is _release/202312-03_

**Comment by markconroy** [comment]
What's in _release/202312-03_? Is 01 and 01 merged to that?

**Comment by Polynya** [comment]
Yes, 01, 02 and main

**Pull request closed without merging**
