### PR TITLE
Release mark 202301 01

### PR DESCRIPTION
**Pull request by markconroy**
- Organises add-content menu items #351 
- sets preview as optional for all content types #352 
- enables localgov_login_redirect module #347 
- sets max-width for text component #349 
- allows CSV files to be uploaded to media document #356 
- re-enables tabs block #357 
- add [Draft] to unpublished pages
- advanced layouts #343
- sets tabs region to sticky for logged in users #363

### CODE REVIEW

**Comment by willguv** [comment]
As agreed @Polynya @MatthewWilkes

**Comment by markconroy** [comment]
I think this one is ready to be deployed now as soon as you get a chance @Polynya 

Thanks very much.

**Comment by Polynya** [comment]
@markconroy looks good. 

Can you change to a new branch name e.g. _release/mark-202401-01_
The prefix _release/_ (not _release-_) allows the branch to be deployed to Preprod and Prod
(The PR won't be merged until after it has been signed off on Preprod.)

Also, on Preprod can you uninstall the Workbench modules and any others that are not in the new release. Otherwise, the deployment will fail because the modules won't exist after _composer install_

**Comment by markconroy** [comment]
@Polynya 

There are fields and taxonomies created as part of the content access work. Disabling those modules will not delete those fields. Will that affect this deployment? We don't want those fields on live (yet) for example.

**Comment by Polynya** [comment]
The deployment will delete the fields during config-import. The taxonomy terms have to be deleted before the vocabulary can be deleted.

I've tried this locally with a database from Preprod from December. These are the steps I had to do manually before running the deployment:

- Remove _Site_Section_ scheme from Workbench Access
- Uninstall _ECC Devolved Editor_
- Uninstall _LocalGov Content Access Control_
- Uninstall _Workbench Access_
- Uninstall _Workbench_
- Delete _Access Control_ vocabulary and taxonomy terms

It's probably best for me to backup the Preprod database first. I can do that tomorrow morning.

**Comment by markconroy** [comment]
Let me know when you have the DB backed up and I'll get those modules uninstalled then.

> The deployment will delete the fields during config-import.

The config for these fields is not in the `config/default` directory on preprod yet so? It's just in the `config/install` directory of the modules and the database of preprod. Is that right?

**Comment by siliconmeadow** [comment]
> 3. A new branch has been created release/mark-202301-01 (sorry, I forgot it was 2024 now!)

Happy New Year!

**Comment by siliconmeadow** [comment]
It looks like it might need a new PR using the new branch with the same description @markconroy. I can't see a way to edit a PR to change the branch you want to merge. I'm happy to do that for you as you've gone through all the details already.

**Comment by Polynya** [comment]
The configuration for the new modules is in `config/default` in the branch that is currently on Preprod e.g.
https://github.com/essexcountycouncil/essex-gov-uk-drupal/blob/3ac2d1dc14d9d51fa67a9431701d51c8721fb89e/config/default/core.entity_form_display.node.localgov_services_page.default.yml#L10
It's not in the new release ... 
https://github.com/essexcountycouncil/essex-gov-uk-drupal/blob/release-mark-202301-01/config/default/core.entity_form_display.node.localgov_services_page.default.yml#L10
... so the configuration import will remove it from the database. The problems occur when configuration you want to delete is still used by content entities, e.g. taxonomy terms.

**Comment by Polynya** [comment]
I've taken the database dump, so can you do the manual steps @markconroy ?

**Comment by markconroy** [comment]
I have those modules uninstalled now, and the taxonomy terms/vocabulary deleted

**Comment by Polynya** [comment]
I have deployed release/mark-202301-01 to Proprod

**Comment by markconroy** [comment]
@willguv Can you give the items on preprod a test and make sure you're happy with them so we can deploy to live?

**Comment by willguv** [comment]
Thanks @markconroy and @Polynya 

I’ll have a look in the morning and let Jen and the team know to check too

Let’s not deploy on Friday - shall we aim for close of play Monday?

**Comment by markconroy** [comment]
Has this been deployed? It seems to be on PROD but when I do a git pull on `main` I am not getting any updated code.

**Comment by Polynya** [comment]
Can you review the PR from the new branch https://github.com/essexcountycouncil/essex-gov-uk-drupal/pull/367

When that's merged I think this PR will be closed automatically.

**Pull request merged**
