### PR TITLE
ECCW-548: Enable health check module

### PR DESCRIPTION
**Pull request by MatthewWilkes**
This enables a healthcheck endpoint on the container app, to be used for replica probes.

### CODE REVIEW

**Comment by siliconmeadow** [comment]
Might we want to use https://www.drupal.org/project/health_check_url so that the url alias `/health` remains free for content, or redirection? And then perhaps an arbitrary, nonsense string could be used instead?

**Comment by siliconmeadow** [comment]
> @siliconmeadow It's a good point, I did wonder that also. Health is a very generic URI. We already have /health coded into the nginx config though, and use this module on other projects. I picked this for consistency, do you think it's worth switching?

What's weird is that I tried this branch on my Linux laptop and I had a version of the database that had a redirect to `/health` already, or so it seemed. Had that not happened, I'd never have asked! I _do_ see that in production that `/health` currently doesn't exist.

@keelanfh - do you mind if we grab `/health` as an endpoint?

**Review by siliconmeadow — CHANGES_REQUESTED** [review]
@MatthewWilkes - I'm happy to swap modules, and export config on this PR if you like.

**Comment by MatthewWilkes** [comment]
@siliconmeadow I've updated it

**Pull request merged**
