### PR TITLE
Feature/advanced layouts

### PR DESCRIPTION
**Pull request by markconroy**
Adds advanced layouts (LocalGov Layouts module) to subsites, so we can have background colours on layout sections, different widths per section, space between items in sections, etc.

This is also how the LGD Microsites work.

### CODE REVIEW

**Review by Polynya — DISMISSED** [review]
Looks good, thanks.

**Comment by markconroy** [comment]
@Polynya Thanks. What do I/you/we need to do now to merge this to `main` and get it deployed to the live site?

**Comment by Polynya** [comment]
I've created a new branch from main - _release/202311-advanced-layouts_ and changed the base branch for this PR. This is because our Gitlab pipelines only allow release branches to be deployed. If the PR still looks ok, please merge it. Then:

- I'll deploy it to Dev for a quick check
- I'll deploy it to Preprod
- You and Will check it on Preprod
- If all ok, you create a PR from the release branch to main
- Will and I agree a time to deploy to Prod - should be at a quiet time for the website and when I can be available for a couple of hours, in case things go wrong
- I'll merge the release branch into main

**Comment by markconroy** [comment]
PR for release: https://github.com/essexcountycouncil/essex-gov-uk-drupal/pull/346

**Comment by Polynya** [comment]
Please close this PR as it's already merged into release/202312-01. Only release branches should be merged to main.

**Pull request closed without merging**
